

domain: felipelobel.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url: https://felipelobel.com/  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /      # place folder name if the site is served in a subfolder

# url:
# baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:collection
  projects:
    output: true
    permalink: /project/:collection


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "assets"
    values:
      assets: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "researches"
    values:
      layout: "research"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
